# Generated by Django 6.0.4 on 2026-04-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='activity_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('activity', 'Activity')], default='assignment', max_length=20),
        ),
    ]
