# Generated by Django 5.2.1 on 2026-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_assignment_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
