# Generated by Django 5.2.1 on 2026-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
